version: '3.8'

services:
  apache:
    container_name: apache
    build:
      context: ./docker/dev/api/
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
